name: Terraform Destroy (AWS)

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2   # change if needed

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
